services:
  funasr_server:
    build:
      context: ./funasr_server
      dockerfile: Dockerfile
    container_name: funasr_server
    restart: unless-stopped
    privileged: true
    command: >
      /bin/bash -c "
      echo '🔄 初始化模型目录...' &&
      mkdir -p /workspace/models &&
      cd /workspace/models &&
      git lfs install &&
      echo '✅ Git LFS 初始化完成' &&
      echo '📥 下载语音识别模型...' &&
      if [ ! -d 'speech_paraformer-large_asr_nat-zh-cantonese-en-16k-vocab8501-online' ]; then
        git clone https://huggingface.co/packetingz/speech_paraformer-large_asr_nat-zh-cantonese-en-16k-vocab8501-online;
        echo '✅ 模型下载完成';
      else
        echo '⚡ 模型已存在，跳过下载';
      fi &&
      echo '🔄 检查和转换模型格式...' &&
      cd /workspace/models &&
      if [ ! -f 'speech_paraformer-large_asr_nat-zh-cantonese-en-16k-vocab8501-online/model_quant.onnx' ] || [ ! -f 'speech_paraformer-large_asr_nat-zh-cantonese-en-16k-vocab8501-online/decoder_quant.onnx' ]; then
        echo '🔧 转换PT模型为ONNX模型...' &&
        funasr-export ++model=speech_paraformer-large_asr_nat-zh-cantonese-en-16k-vocab8501-online ++Quantize=false &&
        echo '✅ 模型转换完成' &&
        echo '📝 重命名ONNX文件...' &&
        cd speech_paraformer-large_asr_nat-zh-cantonese-en-16k-vocab8501-online &&
        if [ -f 'decoder.onnx' ]; then mv decoder.onnx decoder_quant.onnx; fi &&
        if [ -f 'model.onnx' ]; then mv model.onnx model_quant.onnx; fi &&
        echo '✅ 模型文件重命名完成';
      else
        echo '⚡ ONNX模型已存在，跳过转换';
      fi &&
      echo '📋 模型目录文件列表:' &&
      ls -la /workspace/models/speech_paraformer-large_asr_nat-zh-cantonese-en-16k-vocab8501-online/ &&
      echo '✅ 模型准备完成' &&
      chmod +x run_server_2pass.sh parse_options.sh &&
      cd /workspace &&
      echo '🚀 启动FunASR服务器...' &&
      bash run_server_2pass.sh &&
      tail -f /dev/null
      "
    volumes:
      - ./funasr_server:/workspace
    networks:
      - funasr_network

  redis_server:
    image: redis:7-alpine
    container_name: redis_server
    restart: unless-stopped
    networks:
      - funasr_network

  web_server:
    build:
      context: ./web_server
      dockerfile: Dockerfile
    container_name: web_server
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "32796:8443"
    volumes:
      - ./web_server:/workspace
    depends_on:
      - redis_server
      - funasr_server
    environment:
      - DJANGO_SETTINGS_MODULE=ai_chat_server.settings
      - REDIS_HOST=redis_server
      - REDIS_PORT=6379
      - FUNASR_HOST=funasr_server
      - DATABASE_PATH=/workspace/data/db.sqlite3
    networks:
      - funasr_network

networks:
  funasr_network:
    driver: bridge