# Generated by Django 5.2.3 on 2025-08-01 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='tts_api_key',
            field=models.CharField(default='', help_text='DashScope TTS API密钥', max_length=200),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='tts_enabled',
            field=models.BooleanField(default=False, help_text='启用TTS功能'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='tts_model',
            field=models.CharField(default='cosyvoice-v2', help_text='TTS模型', max_length=50),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='tts_sample_rate',
            field=models.IntegerField(choices=[(8000, '8kHz'), (16000, '16kHz'), (22050, '22.05kHz'), (24000, '24kHz'), (44100, '44.1kHz'), (48000, '48kHz')], default=22050, help_text='TTS采样率'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='tts_voice',
            field=models.CharField(default='longxiaochun_v2', help_text='TTS音色', max_length=50),
        ),
    ]
