# Generated by Django 5.2.3 on 2025-08-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_systemconfig_tts_api_key_systemconfig_tts_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='ai_system_prompt',
            field=models.TextField(default='你是一个AI语音助手，请尽可能简短自然的回答用户，你的回答将直接被转换为语音播放给用户，要考虑语音播放的时长。', help_text='AI助手的系统提示词，用于定义AI的角色和行为'),
        ),
    ]
